In [2]:
#reading file 
import pandas as pd
with open('EV_sales.csv') as E:
    ev=pd.read_csv(E)
ev

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,1,2021,Andhra Pradesh,BYD,Electric Scooter,2106,30
1,2,2022,Gujarat,Tata,Electric Bike,4567,13
2,3,2025,Tamil Nadu,Tata,Electric Car,867,29
3,4,2022,Maharashtra,Mahindra,Electric Car,4697,27
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37
...,...,...,...,...,...,...,...
145,146,2021,Andhra Pradesh,MG,Electric Scooter,706,75
146,147,2021,Telangana,Ola,Electric Bike,2589,12
147,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30
148,149,2025,Tamil Nadu,MG,Electric Scooter,2535,56
149,150,2023,Maharashtra,Mahindra,Electric Car,912,28

### Grouping
17. What is the total EV sales for each manufacturer?
18. What is the average EV sales for each state?
19. What is the total EV sales for each vehicle type?
20. What is the total EV sales in each year?
21. What is the average battery capacity for each manufacturer?

In [3]:
#17. What is the total EV sales for each manufacturer?
ev.groupby("Manufacturer")["EVSales"].sum().reset_index()

  Manufacturer  EVSales
0        Ather    69996
1          BYD    70180
2           MG    48237
3     Mahindra    89843
4          Ola    63383
5         Tata    53688

In [4]:
#18. What is the average EV sales for each state?
ev.groupby("State")["EVSales"].mean().round().reset_index().rename(columns={"EVSales":"Average_sales"})

            State  Average_sales
0  Andhra Pradesh         2716.0
1         Gujarat         2917.0
2       Karnataka         2201.0
3     Maharashtra         2523.0
4      Tamil Nadu         2667.0
5       Telangana         2664.0

In [5]:
#19. What is the total EV sales for each vehicle type?
ev.groupby("VehicleType")["EVSales"].sum().reset_index().rename(columns={"EVSales":"Total sales"})

        VehicleType  Total sales
0     Electric Bike       135626
1      Electric Car       119444
2  Electric Scooter       140257

In [6]:
#20. What is the total EV sales in each year?
ev.groupby("Year")["EVSales"].sum().reset_index().rename(columns={"EVSales":"Total sales"})

   Year  Total sales
0  2021        66001
1  2022        94342
2  2023        71154
3  2024        94567
4  2025        69263

In [7]:
#21. What is the average battery capacity for each manufacturer?
ev.groupby("Manufacturer")["BatteryCapacity"].mean().reset_index().rename(columns={"BatteryCapacity":"Average Battery Capacity"})

  Manufacturer  Average Battery Capacity
0        Ather                 30.115385
1          BYD                 39.428571
2           MG                 44.250000
3     Mahindra                 41.379310
4          Ola                 38.230769
5         Tata                 31.333333

###  Sorting
22. What are the top 10 highest EV sales records?
23. What are the bottom 10 EV sales records?
24. Which manufacturers rank highest to lowest in total sales?
25. Which states rank highest to lowest in total EV sales?
26. Which vehicle types rank highest to lowest in total sales?

In [8]:
#22. What are the top 10 highest EV sales records?
ev.sort_values(by="EVSales",ascending=False).head(10).reset_index(drop=True)

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,140,2023,Gujarat,Mahindra,Electric Bike,4988,38
1,131,2023,Karnataka,Ather,Electric Scooter,4983,37
2,148,2022,Andhra Pradesh,Mahindra,Electric Scooter,4983,30
3,98,2024,Gujarat,Mahindra,Electric Bike,4977,42
4,5,2025,Tamil Nadu,Ola,Electric Scooter,4927,37
5,36,2022,Andhra Pradesh,Ather,Electric Car,4919,72
6,55,2025,Andhra Pradesh,MG,Electric Bike,4881,74
7,79,2021,Andhra Pradesh,Ather,Electric Car,4856,35
8,10,2023,Gujarat,Mahindra,Electric Scooter,4829,26
9,118,2022,Tamil Nadu,BYD,Electric Car,4720,29

In [9]:
#23. What are the bottom 10 EV sales records?
ev.sort_values(by="EVSales",ascending=False).tail(10).reset_index(drop=True)

,RecordID,Year,State,Manufacturer,VehicleType,EVSales,BatteryCapacity
0,116,2025,Andhra Pradesh,Ather,Electric Car,662,7
1,53,2021,Maharashtra,Tata,Electric Car,661,10
2,30,2021,Karnataka,Ather,Electric Car,574,32
3,42,2023,Tamil Nadu,MG,Electric Scooter,543,14
4,65,2023,Maharashtra,MG,Electric Scooter,516,13
5,21,2022,Maharashtra,MG,Electric Car,485,16
6,70,2022,Andhra Pradesh,Ather,Electric Scooter,426,47
7,111,2024,Telangana,Mahindra,Electric Bike,320,52
8,120,2022,Karnataka,Tata,Electric Bike,310,41
9,95,2024,Tamil Nadu,Ola,Electric Car,145,15

In [10]:
#24. Which manufacturers rank highest to lowest in total sales?
ev.groupby("Manufacturer")[["EVSales"]].sum().sort_values(by="EVSales",ascending=False).reset_index()

  Manufacturer  EVSales
0     Mahindra    89843
1          BYD    70180
2        Ather    69996
3          Ola    63383
4         Tata    53688
5           MG    48237

In [11]:
#25. Which states rank highest to lowest in total EV sales?
ev.groupby("State")[["EVSales"]].sum().sort_values(by="EVSales",ascending=False).reset_index()

            State  EVSales
0      Tamil Nadu    88012
1  Andhra Pradesh    86896
2         Gujarat    70000
3       Telangana    55953
4     Maharashtra    50455
5       Karnataka    44011

In [13]:
#26. Which vehicle types rank highest to lowest in total sales?
ev.groupby("VehicleType")["EVSales"].sum().sort_values(ascending=False).reset_index()

        VehicleType  EVSales
0  Electric Scooter   140257
1     Electric Bike   135626
2      Electric Car   119444